### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by ghost** [Onkelsam/VNDBUpdater#1]
Hello
I'm unable to login to the app. Attached is event log.
[Eventlog.txt](https://github.com/Onkelsam/VNDBUpdater/files/531765/Eventlog.txt)
![screenshot vndb updator](https://cloud.githubusercontent.com/assets/13769570/19416652/8ed7731e-93af-11e6-8dc0-5a591cc855ef.png)

**Comment by Onkelsam** [comment]
Hi, sorry that my response is so late.

Never encountered that error personally. But what I gather from the error message vndb doesn't respond to your connection request. Do you have any special connection setup (vpn, etc.)?

**Comment by ghost** [comment]
Thank you for your response. My ISP must have blocked some ports because it worked fine when I used a VPN after seeing your question. It's working perfectly now!
I'd like to make a few suggestions.
1. The character information scrolls with the character image.
2. Rendering the images/screenshots in a horizontal row.
3. A gallery mode to scroll images instead of selecting each individually.
4. A choice of the various themes offered by VNDB.
5. A filter box for the tags in the Create Filters window so that navigating is easier. Scrolling through hundreds of tags is a bit.
6. Does your app cache the images? Because it would be nice if it did. Faster and all that.
7. Selecting various tags as favourite highlights/brings them to the top of the list in the tag browser.
8. Color coded tags as in sexual tags have red color, Technical Green and so on. Kinda like that stylish theme.
![upload](https://cloud.githubusercontent.com/assets/13769570/19828734/c2b7de5c-9de7-11e6-8cef-7bc411c64115.png)
9. A way to filter by Developer, Artist, Scenario Creator. Language.
10. Ability to set exe paths and create walkthroughs when offline.  
![upload](https://cloud.githubusercontent.com/assets/13769570/19828891/2e4b95ec-9dec-11e6-8a58-5c6de36130e5.png)

**Comment by Onkelsam** [comment]
Thanks for your response. Glad that you could fix your problem!

Regarding your suggestions:
1. Will add it to my list.
2. Will add additional options so you can decide which you prefer.
3. Will add additional options so you can decide which you prefer.
4. Don't know about that, will have to talk with the vndb owner if I'm allowed to use them and have to figure out myself how to implement that. But its a good idea.
5. Will add it to my list. For now, you can navigate faster if you enter the first letter of the tag you want to use.
6. No, currently it doesn't and you are right of course. Will add it to my list.
7. Will add it to my list.
8. Will add it to my list.
9. Will add it to my list.
10. Will add it to my list.

I'll plan to implement them, but I'm currently quite busy as my (second to last) semester has begun and I have to complete quite a few projects there. I'm sorry but for the next months I probably wont be able to work on this, as I'll also have to write my bachelor thesis starting next year.

For now, someone else created a vndb client (https://vndb.org/t8111) maybe it has some of the features you listed (or maybe you simply prefer it over my client :) ).

**Comment by ghost** [comment]
Thank you :). Good luck on your projects.
